server:
  port: 8083

spring:
  cloud:
    config:
      uri: http://localhost:8888
      enabled: false
  application:
    name: talent
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/talent
    password: 123456789
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
    
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
