server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/auth
    password: 123456789
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG