version: '3.1'
services:
  postgres:
    container_name: "PSQL_PROD"
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      PGGATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  backend:
    container_name: "Starlight_Prod"
    build:
      context: .
      dockerfile: Dockerfile
#    environment:
#      DB_LOGIN: admin
#      DB_PASSWORD: 123456
#      DB_URL: postgres:5432/postgres
#      MAIL_USER: java.team.maksym@gmail.com
#      MAIL_PASSWORD: SoftServe123!
    volumes:
      - backend:/data/backend
    ports:
      - '8080:8080'
    networks:
      - postgres
    restart: unless-stopped

#  pgadmin:
#    container_name: pgadmin_prod
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: sekret7d@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: serg12345
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
#  pgadmin: