server:
  port: 8084

spring:
  cloud:
    config:
      uri: http://localhost:8888
      enabled: false
  application:
    name: sponsor
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/sponsor
    password: 123456789
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    username: java.team.maksym@gmail.com
    password: SoftServe123!

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG