server:
  port: 8082

spring:
  application:
    name: gateway
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://AUTH/.well-known/jwks.json
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  secret: FVUdfgJIfJOPOHnfdUDGFsgJN

