server:
  port: 8082

spring:
  application:
    name: gateway
  jackson:
    property-naming-strategy: SNAKE_CASE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: talent
          uri: lb://TALENT
          predicates:
            - Path=/api/v1/**
            - Path=/api/v2/**
            - Path=/api/v3/**
        - id: sponsor
          uri: lb://SPONSOR
          predicates:
            - Path=/api/v1/**
            - Path=/api/v2/**
            - Path=/api/v3/**
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/**
            - Path=/api/v2/**
            - Path=/api/v3/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
