server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: talent
          uri: lb://TALENT
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
        - id: sponsor
          uri: lb://SPONSOR
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
        - id: authorization
          uri: lb://AUTH
          predicates:
            - Path=/api/**

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

